### ISSUE TITLE
Struggling :(

### ISSUE THREAD

**Issue by jamesryanbell** [smith-kyle/nodegit-flow#7]
Hi

It's probably something daft that I am doing wrong but I am struggling to get this working, I have included the code I am using below, any help would be appreciated.

I know this isn't technically an issue but I am worried I will lose all of my hair with this at the rate I am going! :)

```
var NodeGit   = require('nodegit-flow');
NodeGit.Clone("https://github.com/accountname/repo_name.git', repoPath, gitOptions)
.then(function(repository) {
    	NodeGit.Flow.init(repository, NodeGit.Flow.getConfigDefault());
})
.catch(function(err) { console.log(err); });
```

Thanks,
James

**Comment by smith-kyle** [comment]
you'll be able to see the error message if you return within the then

```javascript
(function(repository) {
        return NodeGit.Flow.init(repository, NodeGit.Flow.getConfigDefault());
})
```
